CREATE TABLE CLAIM_ACCOUNTS (ID BIGINT IDENTITY NOT NULL, EMAIL VARCHAR, FIRST_NAME VARCHAR, LAST_NAME VARCHAR, MIDDLE_NAME VARCHAR, PRIMARY KEY (ID));
CREATE TABLE CLAIM_STATUS (ID BIGINT NOT NULL, NAME VARCHAR, PRIMARY KEY (ID));
CREATE TABLE OP_CLAIMS (ID BIGINT IDENTITY NOT NULL, DT_CREATE TIMESTAMP, NAME VARCHAR, FROM_ACCOUNT_ID BIGINT NOT NULL, STATUS_ID BIGINT NOT NULL, TO_ACCOUNT_ID BIGINT NOT NULL, PRIMARY KEY (ID));

ALTER TABLE OP_CLAIMS ADD CONSTRAINT FK_OP_CLAIMS_TO_ACCOUNT_ID FOREIGN KEY (TO_ACCOUNT_ID) REFERENCES CLAIM_ACCOUNTS (ID);
ALTER TABLE OP_CLAIMS ADD CONSTRAINT FK_OP_CLAIMS_FROM_ACCOUNT_ID FOREIGN KEY (FROM_ACCOUNT_ID) REFERENCES CLAIM_ACCOUNTS (ID);
ALTER TABLE OP_CLAIMS ADD CONSTRAINT FK_OP_CLAIMS_STATUS_ID FOREIGN KEY (STATUS_ID) REFERENCES CLAIM_STATUS (ID);