-- Статусы заявок
INSERT INTO CLAIM_STATUS(ID, NAME) VALUES (1, 'Новая');
INSERT INTO CLAIM_STATUS(ID, NAME) VALUES (2, 'На рассмотрении');
INSERT INTO CLAIM_STATUS(ID, NAME) VALUES (3, 'Выполнена');
INSERT INTO CLAIM_STATUS(ID, NAME) VALUES (4, 'Отклонена');